<?php
session_name('sess_it'); 
session_start();
if (!isset($_SESSION['user']) || $_SESSION['usertype'] != 'it') {
    header("location: ../login.php");
    exit();
}

// Enable error reporting for debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// Import database connection and Firebase Factory
// Make sure this file returns $database and $factory objects.
include("../connection.php");

// Handle Specialty Addition separately
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['save_specialty'])) {
    $specialtyName = trim($_POST['specialty_name']);

    if (!empty($specialtyName)) {
        // Generate a Firebase push key for uniqueness
        $newSpecialtyRef = $database->getReference('specialties')->push();
        $newId = $newSpecialtyRef->getKey(); // Unique key generated by Firebase

        $newSpecialty = [
            'id' => $newId,
            'sname' => $specialtyName
        ];

        // Insert into Firebase
        $newSpecialtyRef->set($newSpecialty);

        echo "<!DOCTYPE html>
        <html>
        <head>
            <meta charset='UTF-8'>
            <title>Specialty Added</title>
        </head>
        <body>
            <script>
                alert('Specialty added successfully!');
                window.location.href='cms.php';
            </script>
        </body>
        </html>";
        exit;
    } else {
        echo "<!DOCTYPE html>
        <html>
        <head>
            <meta charset='UTF-8'>
            <title>Error</title>
        </head>
        <body>
            <script>
                alert('Specialty name cannot be empty.');
                window.history.back();
            </script>
        </body>
        </html>";
        exit;
    }
}

// For all other CMS updates
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    try {
        // Initialize reference for CMS data
        $cmsReference = $database->getReference('cms');
        $currentData  = $cmsReference->getValue(); // Fetch existing data
        $cmsData      = $currentData ?? [];        // Ensure we have an array to merge new data

        // HOME PAGE CONTENT
        if (isset($_POST['save_home'])) {
            $homeTitle = trim($_POST['home_title'] ?? '');
            $mission   = trim($_POST['mission'] ?? '');
            $vision    = trim($_POST['vision'] ?? '');
            $services  = trim($_POST['services'] ?? '');

            if ($homeTitle !== '') {
                $cmsData['home_title'] = $homeTitle;
            }
            if ($mission !== '') {
                $cmsData['mission'] = $mission;
            }
            if ($vision !== '') {
                $cmsData['vision'] = $vision;
            }
            if ($services !== '') {
                $cmsData['services'] = $services;
            }
            $successMessage = "Home page content updated successfully!";
        }

        // ANNOUNCEMENTS
        elseif (isset($_POST['save_announcements'])) {
            $announcementPatient = trim($_POST['announcement_patient'] ?? '');
            $announcementDoctor  = trim($_POST['announcement_doctor'] ?? '');

            if ($announcementPatient !== '') {
                $cmsData['announcement_patient'] = $announcementPatient;
            }
            if ($announcementDoctor !== '') {
                $cmsData['announcement_doctor'] = $announcementDoctor;
            }
            $successMessage = "Announcements updated successfully!";
        }

        // CONTACT INFORMATION
        elseif (isset($_POST['save_contact'])) {
            $contactEmail   = trim($_POST['contact_email'] ?? '');
            $contactPhone   = trim($_POST['contact_phone'] ?? '');
            $contactAddress = trim($_POST['contact_address'] ?? '');

            $deptEmergency    = trim($_POST['dept_emergency'] ?? '');
            $deptOutpatient   = trim($_POST['dept_outpatient'] ?? '');
            $deptCustomer     = trim($_POST['dept_customer'] ?? '');
            $deptAdmitting    = trim($_POST['dept_admitting'] ?? '');
            $deptRadiology    = trim($_POST['dept_radiology'] ?? '');
            $deptCardioPulmo  = trim($_POST['dept_cardiopulmo'] ?? '');
            $deptLaboratory   = trim($_POST['dept_laboratory'] ?? '');
            $deptMolecular    = trim($_POST['dept_molecular'] ?? '');

            if ($contactEmail !== '') {
                $cmsData['contact_email'] = $contactEmail;
            }
            if ($contactPhone !== '') {
                $cmsData['contact_phone'] = $contactPhone;
            }
            if ($contactAddress !== '') {
                $cmsData['contact_address'] = $contactAddress;
            }

            if ($deptEmergency !== '')    $cmsData['dept_emergency'] = $deptEmergency;
            if ($deptOutpatient !== '')   $cmsData['dept_outpatient'] = $deptOutpatient;
            if ($deptCustomer !== '')     $cmsData['dept_customer']  = $deptCustomer;
            if ($deptAdmitting !== '')    $cmsData['dept_admitting'] = $deptAdmitting;
            if ($deptRadiology !== '')    $cmsData['dept_radiology'] = $deptRadiology;
            if ($deptCardioPulmo !== '')  $cmsData['dept_cardiopulmo'] = $deptCardioPulmo;
            if ($deptLaboratory !== '')   $cmsData['dept_laboratory'] = $deptLaboratory;
            if ($deptMolecular !== '')    $cmsData['dept_molecular']  = $deptMolecular;

            $successMessage = "Contact information updated successfully!";
        }

        // BANNER UPLOAD (to Firebase Storage)
        elseif (isset($_POST['save_banner'])) {
            if (isset($_FILES['banner']) && $_FILES['banner']['error'] == 0) {
                // Create a safe filename
                $filename     = basename($_FILES['banner']['name']);
                $safeFilename = preg_replace('/[^a-zA-Z0-9-_\.]/', '', $filename);

                // Use the Firebase Storage
                // Ensure you have $factory set up properly in connection.php
                $storage = $factory->createStorage();
                
                // Replace with your actual bucket name (from Firebase console)
                $bucketName = 'therapease-d9525.appspot.com'; 
                $bucket     = $storage->getBucket($bucketName);

                // Upload the file
                $fileStream = fopen($_FILES['banner']['tmp_name'], 'r');
                $object = $bucket->upload($fileStream, [
                    'name' => $safeFilename
                ]);

                
                 $object->update(['acl' => []], ['predefinedAcl' => 'PUBLICREAD']);

                // Build a public URL (assuming it's publicly readable)
                // If you haven't set the file to public, you'll need to generate a signed URL.
                $bannerUrl = "https://storage.googleapis.com/{$bucketName}/{$safeFilename}";

                // Save that URL to your CMS data
                $cmsData['banner'] = $bannerUrl;
                
                $successMessage = "Banner image uploaded to Firebase Storage successfully!";
            }
        }

        
        if (!empty($cmsData)) {
            $cmsReference->set($cmsData);
            // Output HTML with JavaScript alert and redirect
            echo "<!DOCTYPE html>
            <html>
            <head>
                <meta charset='UTF-8'>
                <title>Update Successful</title>
            </head>
            <body>
                <script>
                    alert('{$successMessage}');
                    window.location.href = 'cms.php';
                </script>
            </body>
            </html>";
            exit();
        } else {
            // No changes
            echo "<!DOCTYPE html>
            <html>
            <head>
                <meta charset='UTF-8'>
                <title>No Changes</title>
            </head>
            <body>
                <script>
                    alert('No changes to save.');
                    window.location.href = 'cms.php';
                </script>
            </body>
            </html>";
            exit();
        }
    } catch (Exception $e) {
        echo "Error: " . $e->getMessage();
    }
} else {
    header("location: cms.php");
}
?>
